Check that iconv command exists
libiconv and thus the iconv command may not be present in a cygwin installation.

This PR adds a check for the availability of iconv on PATH.

Without this check apt-cyg reports very misleading error messages as iconv is called indirectly in a subshell via an eval command. This results in apt-cyg not aborting when the command is not present.

Without this PR:
```
$ apt-cyg find upx
cygpath: can't convert empty path
/usr/local/bin/apt-cyg: line 535: declare: last_cache: not found
/usr/local/bin/apt-cyg: line 535: declare: last_mirror: not found
Cache directory is
Mirror is
Updating setup.ini
/x86_64/setup.bz2: Scheme missing.
/x86_64/setup.bz2.sig: Scheme missing.
/x86_64/setup.ini: Scheme missing.
/x86_64/setup.ini.sig: Scheme missing.
Error: updating setup.ini failed, reverting.
at : /usr/local/bin/apt-cyg: setupini_download: 624

Searching for installed packages matching upx:

Searching for installable packages matching upx:
awk: cmd. line:1: fatal: cannot open file `setup.ini' for reading: No such file or directory
```

With this PR:
```
$ apt-cyg find upx
Error: Required command [iconv] not found.
at : /usr/local/bin/apt-cyg: assert_command_exists: 82
```