Make apt-cyg update work
Summary:
I get "bad signature" errors when I try to run "apt-cyg updates".

Expected:
apt-cyg update
...skip...
signature verified: setup.bz2.sig
...skip...

Actual:
Cache directory is /setup
Mirror is http://cygwin.mirror.constant.com
Updating setup.ini
setup.bz2      100%[=========================================================>]   3.53M  2.53MB/s    in 1.4s
2018-04-23 16:26:24 URL:http://cygwin.mirror.constant.com/x86/setup.bz2 [3700347/3700347] -> "setup.bz2" [1]
setup.bz2.sig  100%[=========================================================>]      72  --.-KB/s    in 0s
2018-04-23 16:26:24 URL:http://cygwin.mirror.constant.com/x86/setup.bz2.sig [72/72] -> "setup.bz2.sig" [1]
Error: BAD signature: setup.bz2.sig

1. Use --verify to avoid "gpg: WARNING: no command supplied.  Trying to guess what you mean ..."
2. Use --keyring pubring.kbx because pubring.gpg does not exist (at least not for my tests)
3. Use --no-default-keyring (I wish I knew exactly why, I just know that gpg returns 2 not 0 if you don't use that)

Even with all of that you still need to interactively set up gpg:
export GNUPGHOME="$cache/.apt-cyg"
gpg --gen-key
gpg --edit-key Cygwin # (set trust to 4)
gpg --edit-key Yaakov